#ifndef MOTIFGPT_TYPES_H
#define MOTIFGPT_TYPES_H

typedef enum {
    PIPE_MSG_TOKEN, PIPE_MSG_STREAM_END, PIPE_MSG_ERROR,
    PIPE_MSG_MODEL_LIST_ITEM, PIPE_MSG_MODEL_LIST_END, PIPE_MSG_MODEL_LIST_ERROR
} pipe_message_type_t;

#endif // MOTIFGPT_TYPES_H
